version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: portfolio_api
    restart: always
    env_file: .env
    ports:
      - "8000:8000"          # 내부 확인용 (Nginx 통해서만 쓰면 생략 가능)
    networks:
      - appnet

  nginx:
    image: nginx:1.27
    container_name: portfolio_nginx
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"              # HTTP
      - "443:443"            # HTTPS (추후 certbot 적용시 사용)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web_build:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # HTTPS 인증서 경로
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
