name: Deploy to EC2 (Docker Compose)

on:
  push:
    branches: [ main ]   # <- 브랜치 이름. main/master/develop에 맞게 바꾸세요.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
    
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: PortfolioPulse/package-lock.json

      # 프론트엔드 빌드 (폴더명이 PortfolioPulse일 때)
      - name: Build frontend
        working-directory: PortfolioPulse
        run: |
            npm cache clean --force
            rm -f package-lock.json
            npm install
            npm run build
        env:
            CI: "true"

      # SSH 설정 (EC2 접속용 키)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # EC2에 프로젝트 동기화
      - name: Rsync project to EC2
        run: |
          rsync -az --delete \
            --exclude ".git" --exclude ".github" \
            --exclude ".env" --exclude ".venv" \
            --exclude "node_modules" --exclude "PortfolioPulse/node_modules" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}/

      # Docker Compose 빌드 & 재시작
      - name: Restart docker compose on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd ${{ secrets.EC2_PATH }}
          docker compose up -d --build
          docker image prune -f
          EOF
